### ISSUE TITLE
Could you please compile and make a release also maybe bump up the NPCLIB Version to 2.11.1

### ISSUE THREAD

**Issue by carlossalcedo1** [A248/NPCSk#5]
**Is your feature request related to something you want to accomplish? Please describe.**
A clear and concise description of what you want to do and why you want this feature.

**Describe the feature you'd like**
A clear and concise description of what you want to have provided.

**Additional context**

**Comment by A248** [comment]
All done; here you are.
https://github.com/A248/NPCSk/releases/tag/0.10.0
